apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478687380031:user/capstone-user
      username: capstone-user
      groups:
        - system:bootstrappers
        - system:nodess