apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - image: theblackdang/capstone:latest
          imagePullPolicy: Always
          name: capstone-app
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
      protocol: TCP