apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: theblackdang/capstone:latest
          imagePullPolicy: Always
          name: capstone-project
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
      protocol: TCP